package com.systemsolution.model;

public enum  RoleName {
	ROLE_PM,
	ROLE_USER,
	ROLE_ADMIN,
	ROLE_CLIENT,
	ROLE_CLIENT_CREATE,
	ROLE_CLIENT_UPDATE,
	ROLE_CLIENT_DELETE,
	ROLE_USERS,
	ROLE_USERS_CREATE,
	ROLE_USERS_ROLES,
	ROLE_USERS_DELETE,
	ROLE_USERS_UPDATE,
	ROLE_SAVINGS_CONSULT,
	ROLE_SAVINGS,
	ROLE_SAVINGS_CREATE,
	ROLE_SAVINGS_PDF,
	ROLE_SAVINGS_MOVEMENTS,
	ROLE_LEND_CONSULT,
	ROLE_LEND_CREATE,
	ROLE_LEND_MOVEMENT,
	ROLE_LEND_CANCEL,
	ROLE_LEND
}